// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Data;

#nullable disable

namespace WebApplication.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1474ca19-ff9f-4a0b-8502-c203e8609e26"),
                            BirthPlace = "Lâm Đồng",
                            DateOfBirth = new DateTime(2000, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Công",
                            Gender = 0,
                            IsGraduated = true,
                            LastName = "Đặng Phan Thành",
                            PhoneNumber = "0375.284.637"
                        },
                        new
                        {
                            Id = new Guid("2d827ff5-420f-4ba2-aae1-478bb9e8dd92"),
                            BirthPlace = "Hà Nội",
                            DateOfBirth = new DateTime(1995, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Linh",
                            Gender = 1,
                            IsGraduated = true,
                            LastName = "Nguyễn Mỹ",
                            PhoneNumber = "0375.284.636"
                        },
                        new
                        {
                            Id = new Guid("c9884941-4d2c-4e57-bcdc-a65dd88bdd11"),
                            BirthPlace = "Hải Phòng",
                            DateOfBirth = new DateTime(2002, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Phương",
                            Gender = 1,
                            IsGraduated = false,
                            LastName = "Nguyễn Thị Mai",
                            PhoneNumber = "0375.284.635"
                        },
                        new
                        {
                            Id = new Guid("e4e77d8f-684d-473e-be17-03c43a076ded"),
                            BirthPlace = "Huế",
                            DateOfBirth = new DateTime(2003, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thu",
                            Gender = 1,
                            IsGraduated = false,
                            LastName = "Phan Thị Hà",
                            PhoneNumber = "0375.284.634"
                        },
                        new
                        {
                            Id = new Guid("f37bcac6-754b-4d7f-9c66-4387f9e98cd7"),
                            BirthPlace = "Hà Nội",
                            DateOfBirth = new DateTime(1994, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Quang",
                            Gender = 0,
                            IsGraduated = false,
                            LastName = "Trần Huy",
                            PhoneNumber = "0375.284.633"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
